server:
  port:8080

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/prescription?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: root
mybatis:
   mapperLocations: classpath:/mapper/*.xml
